const titles={dashboard:'调试环境信息',devices:'充电桩管理',realtime:'实时数据监控',remote:'远程启停充电',fault:'故障码上送',qrcode:'二维码下发',logs:'日志查询',billing:'计费模型',teaching:'教学说明'};
function switchPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelector(`[data-page="${id}"]`).classList.add('active');document.getElementById('pageTitle').textContent=titles[id]||id;if(['devices','remote','realtime'].includes(id))loadDevices();if(id==='logs')loadLogs();if(id==='billing')loadTariff();if(id==='remote')loadTransactions()}
document.querySelectorAll('.nav').forEach(btn=>btn.addEventListener('click',()=>switchPage(btn.dataset.page)));setInterval(()=>document.getElementById('clock').textContent=new Date().toLocaleString(),1000);
document.getElementById('teachBtn').addEventListener('click',e=>{e.currentTarget.classList.toggle('on');e.currentTarget.textContent=e.currentTarget.classList.contains('on')?'教学模式：开':'教学模式：关'});
function typeText(v){return v===0?'直流桩':v===1?'交流桩':'未知'}function netText(v){return v===0?'SIM':v===1?'LAN':v===2?'WAN':'其他'}function statusText(v){return ['离线','故障','空闲','充电中'][v]||`未知(${v})`}function fmt(v,n=1){return Number(v??0).toFixed(n)}
async function api(path,opt={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d}
async function loadDevices(){try{const data=await api('/api/devices'),items=data.items||[];document.getElementById('statTotal').textContent=items.length;document.getElementById('statOnline').textContent=items.filter(x=>x.online).length;document.getElementById('statCharging').textContent=items.filter(x=>x.charge_state==='charging'||(x.realtime&&x.realtime.work_status===3)).length;document.getElementById('statFault').textContent=items.filter(x=>x.realtime&&((x.realtime.fault_bits||0)!==0||x.realtime.work_status===1)).length;const body=document.getElementById('deviceRows');body.innerHTML=items.length?items.map(d=>`<tr><td>${d.pile_code}</td><td>${typeText(d.pile_type)}</td><td>${d.gun_count}</td><td>v${d.protocol_version}</td><td>${d.program_version||'-'}</td><td>${netText(d.network_type)}</td><td><span class="badge ${d.online?'online':'offline'}">${d.online?'在线':'离线'}</span></td><td>${d.charge_state||'idle'}</td><td>0x${Number(d.last_frame_type||0).toString(16).toUpperCase()}</td></tr>`).join(''):'<tr><td colspan="9">暂无设备</td></tr>';['remotePile','rtPile'].forEach(id=>{const sel=document.getElementById(id);if(!sel)return;const old=sel.value;sel.innerHTML=items.map(d=>`<option value="${d.pile_code}">${d.pile_code} · ${typeText(d.pile_type)}</option>`).join('');if(old&&items.some(d=>d.pile_code===old))sel.value=old});if(document.getElementById('realtime').classList.contains('active'))loadRealtime()}catch(e){console.error(e)}}
async function loadRealtime(){const sel=document.getElementById('rtPile');if(!sel||!sel.value)return;try{const d=await api(`/api/devices/${sel.value}/realtime`);document.getElementById('rtVoltage').textContent=`${fmt(d.voltage_v)} V`;document.getElementById('rtCurrent').textContent=`${fmt(d.current_a)} A`;document.getElementById('rtPower').textContent=`${fmt((d.voltage_v||0)*(d.current_a||0)/1000)} kW`;document.getElementById('rtSoc').textContent=`${d.soc_pct??0} %`;document.getElementById('rtEnergy').textContent=`${fmt(d.energy_kwh,4)} kWh`;document.getElementById('rtElapsed').textContent=`${d.elapsed_min??0} min`;document.getElementById('rtRemain').textContent=`${d.remaining_min??0} min`;document.getElementById('rtTemp').textContent=`${d.gun_temp_c??0} ℃`;document.getElementById('rtAmount').textContent=`${fmt(d.amount_yuan,4)} 元`;document.getElementById('rtGun').textContent=d.gun_no||'--';document.getElementById('rtStatus').textContent=statusText(d.work_status);document.getElementById('rtPlugged').textContent=d.gun_plugged===1?'已插枪':d.gun_plugged===0?'未插枪':'未知';document.getElementById('rtFaults').textContent=(d.faults||[]).length?`Bit ${d.faults.join(', ')}`:'无故障';document.getElementById('rtTx').textContent=d.transaction_id||'--';document.getElementById('rtUpdated').textContent=d.updated_at?new Date(d.updated_at*1000).toLocaleTimeString():'--'}catch(e){console.debug(e.message)}}
async function startCharge(){const pile=document.getElementById('remotePile').value,gun=document.getElementById('remoteGun').value,balance=Number(document.getElementById('remoteBalance').value||0),logical=document.getElementById('remoteCard').value;try{const d=await api('/api/charge/start',{method:'POST',body:JSON.stringify({pile_code:pile,gun_no:gun,balance_yuan:balance,logical_card:logical,physical_card:'0000000000000000'})});document.getElementById('controlResult').textContent=`0x34已下发，流水号 ${d.transaction_id}`;setTimeout(loadTransactions,800)}catch(e){document.getElementById('controlResult').textContent='启动失败：'+e.message}}
async function stopCharge(){const pile=document.getElementById('remotePile').value,gun=document.getElementById('remoteGun').value;try{const d=await api('/api/charge/stop',{method:'POST',body:JSON.stringify({pile_code:pile,gun_no:gun})});document.getElementById('controlResult').textContent=`0x36已下发，流水号 ${d.transaction_id}`;setTimeout(loadTransactions,800)}catch(e){document.getElementById('controlResult').textContent='停止失败：'+e.message}}
async function loadTransactions(){try{const d=await api('/api/transactions'),rows=document.getElementById('transactionRows');rows.innerHTML=(d.items||[]).map(x=>`<tr><td>${x.transaction_id||'-'}</td><td>${x.pile_code||'-'}</td><td>${x.gun_no||'-'}</td><td>${x.status||'-'}</td><td>${x.soc_pct??'-'}</td><td>${x.energy_kwh!=null?fmt(x.energy_kwh,4):'-'}</td><td>${x.amount_yuan!=null?fmt(x.amount_yuan,4):'-'}</td></tr>`).join('')||'<tr><td colspan="7">暂无交易</td></tr>'}catch(e){console.error(e)}}
async function loadLogs(){try{const d=await api('/api/logs?limit=100');document.getElementById('logList').innerHTML=(d.items||[]).map(x=>`<div>[${new Date(x.time*1000).toLocaleTimeString()}] [${x.direction==='up'?'上行':'下行'}] ${x.frame_type} ${x.pile_code||''} ${x.summary||''}<br><small>${x.raw_hex||''}</small></div>`).join('')||'暂无日志'}catch(e){document.getElementById('logList').textContent=e.message}}
async function loadTariff(){try{const d=await api('/api/tariff');document.getElementById('rateSharp').textContent=`${fmt(d.sharp,5)} 元/kWh`;document.getElementById('ratePeak').textContent=`${fmt(d.peak,5)} 元/kWh`;document.getElementById('rateFlat').textContent=`${fmt(d.flat,5)} 元/kWh`;document.getElementById('rateValley').textContent=`${fmt(d.valley,5)} 元/kWh`;document.getElementById('serviceFee').textContent=`服务费 ${fmt(d.service_fee,5)} 元/kWh · 模型 ${d.model_code}` }catch(e){console.error(e)}}
function makeQrText(){const s=`zxkcharge://pile/${document.getElementById('qrPile').value}/${document.getElementById('qrGun').value}`;document.getElementById('qrText').textContent=s}
async function verifyFrame(){try{const d=await api('/api/protocol/verify',{method:'POST',body:JSON.stringify({hex_frame:document.getElementById('verifyHex').value})});document.getElementById('verifyResult').textContent=JSON.stringify(d,null,2)}catch(e){document.getElementById('verifyResult').textContent=e.message}}
loadDevices();loadTariff();setInterval(loadDevices,5000);setInterval(()=>{if(document.getElementById('realtime').classList.contains('active'))loadRealtime()},3000);