const titles={dashboard:'调试环境信息',devices:'充电桩管理',realtime:'实时数据监控',remote:'远程启动充电',fault:'故障码上送',qrcode:'二维码下发',logs:'日志查询',billing:'计费模型',teaching:'教学说明'};
function switchPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelector(`[data-page="${id}"]`).classList.add('active');document.getElementById('pageTitle').textContent=titles[id]||id;if(id==='devices'||id==='remote'||id==='realtime')loadDevices()}
document.querySelectorAll('.nav').forEach(btn=>btn.addEventListener('click',()=>switchPage(btn.dataset.page)));
setInterval(()=>document.getElementById('clock').textContent=new Date().toLocaleString(),1000);
document.getElementById('teachBtn').addEventListener('click',e=>{e.currentTarget.classList.toggle('on');e.currentTarget.textContent=e.currentTarget.classList.contains('on')?'教学模式：开':'教学模式：关'});
function typeText(v){return v===0?'直流桩':v===1?'交流桩':'未知'}function netText(v){return v===0?'SIM':v===1?'LAN':v===2?'WAN':'其他'}
function statusText(v){return ['离线','故障','空闲','充电中'][v]||`未知(${v})`}
function fmt(v,n=1){return Number(v??0).toFixed(n)}
async function loadDevices(){try{const r=await fetch('/api/devices');const data=await r.json();const items=data.items||[];document.getElementById('statTotal').textContent=items.length;document.getElementById('statOnline').textContent=items.filter(x=>x.online).length;document.getElementById('statCharging').textContent=items.filter(x=>x.realtime&&x.realtime.work_status===3).length;document.getElementById('statFault').textContent=items.filter(x=>x.realtime&&((x.realtime.fault_bits||0)!==0||x.realtime.work_status===1)).length;const body=document.getElementById('deviceRows');body.innerHTML=items.length?items.map(d=>`<tr><td>${d.pile_code}</td><td>${typeText(d.pile_type)}</td><td>${d.gun_count}</td><td>v${d.protocol_version}</td><td>${d.program_version||'-'}</td><td>${netText(d.network_type)}</td><td><span class="badge ${d.online?'online':'offline'}">${d.online?'在线':'离线'}</span></td><td>0x${Number(d.last_frame_type||0).toString(16).toUpperCase()}</td></tr>`).join(''):'<tr><td colspan="8">暂无设备</td></tr>';['remotePile','rtPile'].forEach(id=>{const sel=document.getElementById(id);if(!sel)return;const old=sel.value;sel.innerHTML=items.map(d=>`<option value="${d.pile_code}">${d.pile_code} · ${typeText(d.pile_type)}</option>`).join('');if(old&&items.some(d=>d.pile_code===old))sel.value=old});if(document.getElementById('realtime').classList.contains('active'))loadRealtime()}catch(e){console.error(e)}}
async function loadRealtime(){const sel=document.getElementById('rtPile');if(!sel||!sel.value)return;try{const r=await fetch(`/api/devices/${sel.value}/realtime`);if(!r.ok)throw new Error('暂无0x13实时数据');const d=await r.json();document.getElementById('rtVoltage').textContent=`${fmt(d.voltage_v)} V`;document.getElementById('rtCurrent').textContent=`${fmt(d.current_a)} A`;document.getElementById('rtPower').textContent=`${fmt((d.voltage_v||0)*(d.current_a||0)/1000)} kW`;document.getElementById('rtSoc').textContent=`${d.soc_pct??0} %`;document.getElementById('rtEnergy').textContent=`${fmt(d.energy_kwh,4)} kWh`;document.getElementById('rtElapsed').textContent=`${d.elapsed_min??0} min`;document.getElementById('rtRemain').textContent=`${d.remaining_min??0} min`;document.getElementById('rtTemp').textContent=`${d.gun_temp_c??0} ℃`;document.getElementById('rtAmount').textContent=`${fmt(d.amount_yuan,4)} 元`;document.getElementById('rtGun').textContent=d.gun_no||'--';document.getElementById('rtStatus').textContent=statusText(d.work_status);document.getElementById('rtPlugged').textContent=d.gun_plugged===1?'已插枪':d.gun_plugged===0?'未插枪':'未知';document.getElementById('rtFaults').textContent=(d.faults||[]).length?`Bit ${d.faults.join(', ')}`:'无故障';document.getElementById('rtTx').textContent=d.transaction_id||'--';document.getElementById('rtUpdated').textContent=d.updated_at?new Date(d.updated_at*1000).toLocaleTimeString():'--'}catch(e){['rtVoltage','rtCurrent','rtPower','rtSoc','rtEnergy','rtElapsed','rtRemain','rtTemp','rtAmount'].forEach(id=>document.getElementById(id).textContent='--');console.debug(e.message)}}
loadDevices();setInterval(loadDevices,5000);setInterval(()=>{if(document.getElementById('realtime').classList.contains('active'))loadRealtime()},3000);
